# main.py

from youtube_virality_worker import run_virality_pass
from transcript_fetcher import fetch_transcript
from leninware_commentary import generate_leninware_commentary
from leninware_video_pipeline import create_leninware_video
from youtube_uploader import upload_video


def main():
    print("[main] Starting Leninware pipeline single pass...")

    # Step 1: pick viral candidates
    viral_candidates = run_virality_pass()
    if not viral_candidates:
        print("[main] No candidates passed virality threshold. Nothing to do.")
        print("[main] Leninware pass complete.")
        return

    # For safety, just process the top 1 candidate per run.
    candidate = viral_candidates[0]
    url = candidate.get("url")
    title = candidate.get("title", "(untitled)")
    channel = candidate.get("channel", "")

    print(f"[main] Selected candidate: {title} ({url}) from {channel}")

    # Step 2: fetch transcript
    transcript = fetch_transcript(url)
    if not transcript:
        print("[main] No transcript returned; aborting this candidate.")
        print("[main] Leninware pass complete.")
        return

    # Step 3: generate Leninware commentary
    print("[main] Generating Leninware commentary...")
    commentary = generate_leninware_commentary(transcript)

    # Step 4: synthesize audio + render video
    print("[main] Creating Leninware video...")
    video_path = create_leninware_video(commentary)

    # Step 5: upload to YouTube
    upload_title = f"Leninware reacts: {title}"
    upload_description = (
        f"Automated Leninware commentary on: {title}\n"
        f"Original channel: {channel}\n\n"
        "Generated by Leninware AI."
    )

    print("[main] Uploading video to YouTube...")
    upload_video(
        video_path,
        title=upload_title,
        description=upload_description,
    )

    print("[main] Leninware pass complete.")


if __name__ == "__main__":
    main()